# Generated by Django 6.0.4 on 2026-04-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé de la catégorie')),
                ('niveau_scolaire', models.CharField(choices=[('Primaire', 'Primaire'), ('Collège', 'Collège'), ('Lycée', 'Lycée')], max_length=50, verbose_name='Niveau Scolaire')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=150, verbose_name='Nom de la société')),
                ('contact', models.CharField(max_length=150, verbose_name='Contact (Email/Tél)')),
                ('delai_livraison', models.IntegerField(help_text='Ex: 15 pour 15 jours', verbose_name='Délai de livraison (en jours)')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Uniforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tenue', models.CharField(choices=[('Chemise', 'Chemise'), ('Pantalon', 'Pantalon'), ('Jupe', 'Jupe'), ('Pull', 'Pull'), ('T-shirt', 'T-shirt'), ('Survêtement', 'Survêtement')], max_length=50, verbose_name='Type de tenue')),
                ('taille', models.CharField(max_length=20, verbose_name='Taille')),
                ('couleur', models.CharField(max_length=50, verbose_name='Couleur')),
                ('quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to='inventory.categorie', verbose_name='Catégorie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uniformes', to='inventory.fournisseur', verbose_name='Fournisseur')),
            ],
        ),
    ]
