# Generated by Django 5.0.14 on 2026-05-10 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniforme',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Uniforme', 'verbose_name_plural': 'Uniformes'},
        ),
        migrations.AddField(
            model_name='uniforme',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'ajout"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniforme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uniformes/', verbose_name='Photo du produit'),
        ),
        migrations.AddField(
            model_name='uniforme',
            name='nom',
            field=models.CharField(default='Uniforme', max_length=200, verbose_name="Nom de l'uniforme"),
        ),
        migrations.AddField(
            model_name='uniforme',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix unitaire (MAD)'),
        ),
    ]
